name: Prettier Check and Format

# 워크플로우가 언제 실행될지 정의하는 부분
on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행
      - frontend_Br # frontend_Br 브랜치에 푸시될 때마다 실행
      - backend_Br # backend_Br 브랜치에 푸시될 때마다 실행
      - branch01 # branch01 브랜치에 푸시될 때마다 실행
  pull_request:
    branches:
      - main # main 브랜치로 PR이 생성될 때마다 실행
      - frontend_Br # frontend_Br 브랜치에 푸시될 때마다 실행
      - backend_Br # backend_Br 브랜치에 푸시될 때마다 실행
      - branch01 # branch01 브랜치에 푸시될 때마다 실행

# Prettier가 동작할 작업들을 정의
jobs:
  prettier:
    runs-on: ubuntu-latest # GitHub Actions에서 사용할 최신 우분투 환경

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 레포지터리 코드를 체크아웃 (다운로드)

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Node.js 환경을 설정
        with:
          node-version: "20" # Node.js 버전 설정

      # 프론트엔드 디펜던시 설치
      - name: Install dependencies for Frontend
        run: npm install --force
        working-directory: ./frontend # 프론트 폴더에서 npm install 실행

      # 백엔드 디펜던시 설치
      - name: Install dependencies for Backend
        run: npm install --force
        working-directory: ./backend # 백 폴더에서 npm install 실행

      # Prettier 설치 (만약 로컬에 설치되지 않았다면)
      - name: Install Prettier
        run: npm install prettier --save-dev
        working-directory: . # 루트 디렉토리에서 실행

      - name: Check code formatting with Prettier
        run: npx prettier --check . # 코드가 Prettier 스타일 규칙에 맞는지 확인
        continue-on-error: true  # --check에서 에러가 나도 다음 단계를 계속 실행하게 함

      - name: Format code with Prettier
        run: npx prettier --write . # 코드 포맷을 Prettier 스타일에 맞게 자동으로 수정
